name: flutter_api_test
description: "Just test api and some packages"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  go_router: ^17.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  riverpod: ^3.4.2
  slang: ^4.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
